-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Graphql.Object.Link exposing (..)

import Graphql.InputObject
import Graphql.Interface
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Object
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.Scalar
import Graphql.ScalarCodecs
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.Union
import Json.Decode as Decode


id : SelectionSet Graphql.ScalarCodecs.Id Graphql.Object.Link
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Graphql.ScalarCodecs.codecs |> Graphql.Scalar.unwrapCodecs |> .codecId |> .decoder)


url : SelectionSet String Graphql.Object.Link
url =
    Object.selectionForField "String" "url" [] Decode.string


title : SelectionSet String Graphql.Object.Link
title =
    Object.selectionForField "String" "title" [] Decode.string


byline : SelectionSet String Graphql.Object.Link
byline =
    Object.selectionForField "String" "byline" [] Decode.string


content : SelectionSet String Graphql.Object.Link
content =
    Object.selectionForField "String" "content" [] Decode.string


textcontent : SelectionSet String Graphql.Object.Link
textcontent =
    Object.selectionForField "String" "textcontent" [] Decode.string


length : SelectionSet Int Graphql.Object.Link
length =
    Object.selectionForField "Int" "length" [] Decode.int


excerpt : SelectionSet String Graphql.Object.Link
excerpt =
    Object.selectionForField "String" "excerpt" [] Decode.string


siteName : SelectionSet String Graphql.Object.Link
siteName =
    Object.selectionForField "String" "siteName" [] Decode.string


image : SelectionSet (Maybe Int) Graphql.Object.Link
image =
    Object.selectionForField "(Maybe Int)" "image" [] (Decode.int |> Decode.nullable)


favicon : SelectionSet (Maybe Int) Graphql.Object.Link
favicon =
    Object.selectionForField "(Maybe Int)" "favicon" [] (Decode.int |> Decode.nullable)
