-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Graphql.Object.LinkConnection exposing (..)

import Graphql.InputObject
import Graphql.Interface
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Object
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.Scalar
import Graphql.ScalarCodecs
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.Union
import Json.Decode as Decode


totalCount : SelectionSet Int Graphql.Object.LinkConnection
totalCount =
    Object.selectionForField "Int" "totalCount" [] Decode.int


nodes :
    SelectionSet decodesTo Graphql.Object.Link
    -> SelectionSet (List decodesTo) Graphql.Object.LinkConnection
nodes object_ =
    Object.selectionForCompositeField "nodes" [] object_ (identity >> Decode.list)


edges :
    SelectionSet decodesTo Graphql.Object.LinkEdge
    -> SelectionSet (List decodesTo) Graphql.Object.LinkConnection
edges object_ =
    Object.selectionForCompositeField "edges" [] object_ (identity >> Decode.list)


pageInfo :
    SelectionSet decodesTo Graphql.Object.PageInfo
    -> SelectionSet decodesTo Graphql.Object.LinkConnection
pageInfo object_ =
    Object.selectionForCompositeField "pageInfo" [] object_ identity
