-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Graphql.Enum.Message exposing (..)

import Json.Decode as Decode exposing (Decoder)


type Message
    = NewLink


list : List Message
list =
    [ NewLink ]


decoder : Decoder Message
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "NEW_LINK" ->
                        Decode.succeed NewLink

                    _ ->
                        Decode.fail ("Invalid Message type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : Message -> String
toString enum =
    case enum of
        NewLink ->
            "NEW_LINK"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Message
fromString enumString =
    case enumString of
        "NEW_LINK" ->
            Just NewLink

        _ ->
            Nothing
