-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Graphql.Mutation exposing (..)

import Graphql.InputObject
import Graphql.Interface
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Object
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.Scalar
import Graphql.ScalarCodecs
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.Union
import Json.Decode as Decode exposing (Decoder)


type alias RemoveLinkRequiredArguments =
    { id : Graphql.ScalarCodecs.Id }


removeLink :
    RemoveLinkRequiredArguments
    -> SelectionSet Bool RootMutation
removeLink requiredArgs =
    Object.selectionForField "Bool" "removeLink" [ Argument.required "id" requiredArgs.id (Graphql.ScalarCodecs.codecs |> Graphql.Scalar.unwrapEncoder .codecId) ] Decode.bool


type alias AddUserRequiredArguments =
    { email : String
    , name : String
    , password : String
    }


addUser :
    AddUserRequiredArguments
    -> SelectionSet decodesTo Graphql.Object.User
    -> SelectionSet decodesTo RootMutation
addUser requiredArgs object_ =
    Object.selectionForCompositeField "addUser" [ Argument.required "email" requiredArgs.email Encode.string, Argument.required "name" requiredArgs.name Encode.string, Argument.required "password" requiredArgs.password Encode.string ] object_ identity
