-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Graphql.Object exposing (..)


type Article
    = Article


type Link
    = Link


type LinkConnection
    = LinkConnection


type LinkEdge
    = LinkEdge


type PageInfo
    = PageInfo


type Project
    = Project


type ProjectConnection
    = ProjectConnection


type ProjectEdge
    = ProjectEdge


type User
    = User
